### ISSUE TITLE
Disable bootup screen?

### ISSUE THREAD

**Issue by k0lourful** [KuromeSan/chovy-sign#14]
Could you kindly point out part of the code, which includes the startup delay? I only managed to remove the splash image, not the delay, however.

**Comment by KuromeSan** [comment]
That's because the delay is litterally just the vita loading pspemu

**Comment by k0lourful** [comment]
Oooh, right! Sorry about that then, I didn't realise how pspemu works.

**Comment by KuromeSan** [comment]
Yes, the bootup screen works the same way the words "Minis" appears or the health and safety warning on games off PSN ^^
